---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lets-encrypt-cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lets-encrypt-cron
  template:
    metadata:
      labels:
        app: lets-encrypt-cron
    spec:
      serviceAccountName: svc-tls-secret-handler
      automountServiceAccountToken: true
      containers:
      - image: 88lexd/lets-encrypt-cron:latest
        imagePullPolicy: Always
        name: lets-encrypt-cron
        command: ["python3"]
        args: ["/app/main.py", "--cluster-config"]
        env:
        - name: TZ
          value: {{ .Values.time_zone }}
        - name: LE_ACCOUNT_KEY_NAME
          value: {{ .Values.lets_encrypt.account_key_secret_name }}
        - name: LE_PRIVATE_KEY_NAME
          value: {{ .Values.lets_encrypt.pivate_key_secret_name }}
        - name: LE_CSR_CONFIGMAP_NAME
          value: {{ .Values.lets_encrypt.csr_configmap_name }}
        volumeMounts:
        - name: wordpress-volume
          mountPath: "/var/www/html"  # Same directory as what the WordPress pods are using. This is where the challenge files will be stored
      volumes:
      - name: wordpress-volume
        persistentVolumeClaim:
          claimName: wordpress-pvc  # Referencing "[PersistentVolumeClaim].metadata.name" in deployment-wordpress.yaml
