apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  serviceAccountName: svc-tls-secret-handler
  automountServiceAccountToken: true
  containers:
  - image: ubuntu
    name: ubuntu
    command: ["/bin/sh", "-c"]
    args: ["sleep infinity"]
