apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: rl-tls-secret-handler
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get"]
  resourceNames: [
    "{{ .Values.lets_encrypt.account_key_secret_name }}",
    "{{ .Values.lets_encrypt.pivate_key_secret_name }}",
    "{{ .Values.lets_encrypt.csr_configmap_name }}"
  ]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["delete"]
  resourceNames: ["{{ .Values.wordpress.ingress_tls_secret_name }}"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rlb-tls-secret-handler
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: rl-tls-secret-handler
subjects:
- kind: ServiceAccount
  name: svc-tls-secret-handler
  namespace: {{ .Release.Namespace }}
