---
- name: Update /etc/hosts for local cluster
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {{ hostvars.masternode.private_ipaddr }} masternode.lexd.local controlplane.lexd.local
      {{ hostvars.workernode1.private_ipaddr }} workernode1.lexd.local

- name: Set OS hostname based on inventory_hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

# /etc/resolv.conf is managed by systemd
- name: Update /etc/systemd/resolved.conf to include lexd.local in search suffix
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^Domains'
    line: "Domains=lexd.local"
    state: present
  register: resolve_conf

- name: Restart systemd-resolved service
  ansible.builtin.service:
    name: systemd-resolved.service
    state: restarted
  when: resolve_conf.changed

- name: Set timezone to Australia/Sydney
  community.general.timezone:
    name: Australia/Sydney

- name: Configure .vimrc (no indent)
  ansible.builtin.lineinfile:
    path: .vimrc  # uses to $HOME/.vimrc
    regexp: "^set autoindent"
    line: "set noautoindent"
    state: present
    create: yes
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Configure .vimrc (set paste)
  ansible.builtin.lineinfile:
    path: .vimrc  # uses to $HOME/.vimrc
    regexp: "^set paste"
    line: "set paste"
    state: present
    create: yes
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Setup bashrc
  ansible.builtin.copy:
    dest: .bashrc.alex  # uses $HOME/.bashrc.alex
    content: |
      # Sys variables
      export HISTSIZE=5000
      export HISTFILESIZE=5000
      export PYTHONSTARTUP=~/.pythonrc
      export EDITOR=vim

      # Force prompt to write history after every command.
      export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Ensure ~/.bashrc sources ~/.bashrc.alex
  ansible.builtin.lineinfile:
    path: .bashrc
    regex: '^source ~/.bashrc.alex'
    line: 'source ~/.bashrc.alex'
    state: present
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Install base dependencies
  ansible.builtin.apt:
    name:
      - python3-pip  # require to install Kubernetes python modules which is used by Ansible
      - jq  # to extract info from kubectl or docker output
      - net-tools  # to troubleshoot network related issues
      - nfs-common  # require on nodes for nfs-subdir to work
      - iotop
      - iftop
    state: present
    update_cache: yes

- name: Install kubernetes python library
  ansible.builtin.pip:
    name: kubernetes
  become_user: "{{ ansible_env.SUDO_USER }}"  # Install as non root user!
