---
- name: Set timezone to Australia/Sydney
  community.general.timezone:
    name: Australia/Sydney

- name: Configure .vimrc (no indent)
  ansible.builtin.lineinfile:
    path: .vimrc  # uses to $HOME/.vimrc
    regexp: "^set autoindent"
    line: "set noautoindent"
    state: present
    create: yes
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Configure .vimrc (set paste)
  ansible.builtin.lineinfile:
    path: .vimrc  # uses to $HOME/.vimrc
    regexp: "^set paste"
    line: "set paste"
    state: present
    create: yes
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Install base dependencies
  ansible.builtin.apt:
    name:
      - snapd  # to install microk8s
      - jq  # to extract info from kubectl or docker output
      - net-tools  # to troubleshoot network related issues
    state: present
    update_cache: yes
