# Configure a machine to act as a jump server. Ensure tools like kubeadm is installed.
---
######################
# Tools install tasks
- name: Showing current version vars being used
  debug:
    var: kubernetes_packages

- name: Setting fact for the kubeadm package
  set_fact:
    kubectl_pkg: "{{ kubernetes_packages | json_query(query) }}"
  vars:
    query: "[?name=='kubectl'] | [0]"  # This is using JMES query to extract the item where name=kubectl from the 'kubernetes_packages' list.

- name: Selected the following kubeadm package info
  debug:
    var: kubectl_pkg

- name: Add Kubernetes GPG key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
    keyring: "{{ k8s_gpg_keyring_path }}"

- name: Add Kubernetes APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ k8s_gpg_keyring_path }}] {{ k8s_repository }}"
    state: present
    filename: kubernetes

- name: "Installing {{ kubectl_pkg.name }} ({{ kubectl_pkg.version }}) "
  ansible.builtin.apt:
    name: "{{ kubectl_pkg.name }} "
    state: present
    update_cache: yes

- name: "APT hold {{ kubectl_pkg.name }} ({{ kubectl_pkg.version }})"
  ansible.builtin.dpkg_selections:
    name: "{{ kubectl_pkg.name }}"
    selection: hold


############################
# Jump Server Configuration
# TODO
