---
- name: Create temp dir to place admin.conf
  ansible.builtin.tempfile:
    state: directory
    prefix: ansible.kubeadm_
  register: local_temp_dir
  delegate_to: localhost
  become: no
  run_once: yes
  tags:
  - admin_conf

- name: Fetching admin.conf from master server
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ local_temp_dir.path }}/"
    flat: yes
  when: inventory_hostname == "masternode"  # inventory_hostname is a magic variable
  tags:
  - admin_conf

- name: Create kubeconfig directory for current user
  ansible.builtin.file:
    path: ".kube/"
    state: directory
  become_user: "{{ ansible_env.SUDO_USER }}"
  when: inventory_hostname == "glusterarb"
  tags:
  - admin_conf

- name: Copy admin.conf over to jumpbox
  ansible.builtin.copy:
    src: "{{ local_temp_dir.path }}/admin.conf"
    dest: ".kube/config"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0600
  when: inventory_hostname == "glusterarb"
  tags:
  - admin_conf

- name: Delete local temp directory
  ansible.builtin.file:
    path: "{{ local_temp_dir.path }}"
    state: absent
  delegate_to: localhost
  when: local_temp_dir.changed
  become: no
  run_once: yes
  tags:
  - admin_conf

- name: Setup kubectl autocomplete
  ansible.builtin.blockinfile:
    path: ~/.bashrc.alex
    block: |
      # kubectl auto complete
      source <(kubectl completion bash)
  become_user: "{{ ansible_env.SUDO_USER }}"
