# Install and enable Gluster
---
- name: Install glusterfs-server
  ansible.builtin.apt:
    name: glusterfs-server
    state: present
    update_cache: yes

- name: Enable and restart glusterd.service
  ansible.builtin.service:
    name: glusterd.service
    enabled: yes
    state: started
