---
- name: Install keepalived
  ansible.builtin.apt:
    name: keepalived
    state: present
    update_cache: yes

- name: Check if /etc/keepalived exist
  stat:
    path: /etc/keepalived
  register: keepalived_path

- name: Create path for keepalived config
  file:
    path: /etc/keepalived
    state: directory
  when: not keepalived_path.stat.exists

- name: Copy config template file over to server
  ansible.builtin.template:
    src: ../templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  register: keepalived_conf

- name: Enable and restart keepalived.service
  ansible.builtin.service:
    name: keepalived.service
    enabled: yes
    state: restarted
  when: keepalived_conf.changed
