# Install and enable Gluster
---
- name: Install glusterfs-server
  ansible.builtin.apt:
    pkg:
    - glusterfs-server
    - glusterfs-client  # although comes with the glusterfs-server package. Adding it here to ensure it's installed.
    state: present
    update_cache: yes

- name: Enable and restart glusterd.service
  ansible.builtin.service:
    name: glusterd.service
    enabled: yes
    state: started
