---
- include_vars:
    name: Include vars for Helm
    file: ../vars/kubernetes.yml

- name: Install Helm binary
  ansible.builtin.unarchive:
    src: "{{ helm_binary_src }}"
    remote_src: yes
    dest: /tmp

- name: Move helm to desired destination
  shell: |
    mv /tmp/linux-amd64/helm /usr/local/bin/helm
    rm -rf /tmp/linux-amd64
