# This is the file which openssl will use to generate the CSR
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.lets_encrypt.csr_configmap_name }}
data:
  csr_details: |
    [req]
    default_bits = 2048
    prompt = no
    default_md = sha256
    req_extensions = req_ext
    distinguished_name = dn

    [ dn ]
    C={{ .Values.lets_encrypt.csr_country }}
    ST={{ .Values.lets_encrypt.csr_state }}
    L={{ .Values.lets_encrypt.csr_location }}
    O={{ .Values.lets_encrypt.csr_org }}
    OU={{ .Values.lets_encrypt.csr_org_unit }}
    emailAddress={{ .Values.lets_encrypt.csr_email }}
    CN = {{ .Values.lets_encrypt.csr_subject_cn }}

    [ req_ext ]
    subjectAltName = @alt_names

    [ alt_names ]
    DNS.1 = {{ .Values.lets_encrypt.csr_subject_cn }}
