#############
# PROD SAMPLE
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: prod
  labels:
    app: flask-service
    env: prod
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: sample-flask
    env: prod
