---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Mi  # this is ignored

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: {{ .Values.grafana.deployment_image }}
        env:
        - name: GF_SMTP_ENABLED
          value: "true"
        - name: GF_SMTP_HOST
          value: smtp-relay.brevo.com:587
        - name: GF_SMTP_STARTTLS_POLICY
          value: MandatoryStartTLS
        - name: GF_SMTP_FROM_ADDRESS
          valueFrom:
            secretKeyRef:
              name: grafana-config-smtp
              key: fromaddr
        - name: GF_SMTP_USER
          valueFrom:
            secretKeyRef:
              name: grafana-config-smtp
              key: username
        - name: GF_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-config-smtp
              key: password
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: 500M
            cpu: "500m"
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc  # Referencing [PersistentVolumeClaim].metadata.name in this deployment manifest
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
