---
- name: Create kubeconfig directory
  ansible.builtin.file:
    path: ".kube"
    state: directory
    mode: 0700
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Copy admin.conf over to nonroot user
  ansible.builtin.copy:
    src: "/etc/kubernetes/admin.conf"
    dest: ".kube/config"
    remote_src: yes
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: 0600

- name: Setup kubectl autocomplete
  ansible.builtin.blockinfile:
    path: ~/.bashrc.kubectl
    block: |
      # kubectl auto complete
      source <(kubectl completion bash)
    create: yes
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Ensure ~/.bashrc sources ~/.bashrc.kubectl
  ansible.builtin.lineinfile:
    path: .bashrc
    regex: '^source ~/.bashrc.kubectl'
    line: 'source ~/.bashrc.kubectl'
    state: present
  become_user: "{{ ansible_env.SUDO_USER }}"
