# The tasks are based off the installation instructions outlined here:
# https://github.com/containerd/containerd/blob/main/docs/cri/installation.md
---
- name: Install required library for seccomp
  ansible.builtin.apt:
    name: libseccomp2
    update_cache: yes
    state: present

- name: Check containerd status
  shell: |
    if [[ $(ps -A | grep containerd) ]]; then
        ps -Af | grep containerd | grep -v grep
    else
        echo "CONTAINERD_NOT_RUNNING"
    fi
  args:
    executable: /bin/bash
  register: containerd_status
  changed_when: False  # Task will return ok instead of changed

# Download then extract on purpose. This way I can inspect the tarball for any issues.
- name: Download containerd tarball
  ansible.builtin.get_url:
    url: "{{ containerd_tarball_url }}"
    dest: "/tmp/{{ containerd_tarball_url.split('/')[-1] }}"
  when: containerd_status.stdout == "CONTAINERD_NOT_RUNNING"
  register: containerd_tarball_dl

- name: Extract containerd tarball at root (/) level
  ansible.builtin.unarchive:
    src: "/tmp/{{ containerd_tarball_url.split('/')[-1] }}"
    remote_src: yes
    dest: /
  when: containerd_status.stdout == "CONTAINERD_NOT_RUNNING"
  register: containerd_unarchived

- name: Remove default CNI config
  ansible.builtin.file:
    path: /etc/cni/net.d/10-containerd-net.conflist
    state: absent
  when: containerd_status.stdout == "CONTAINERD_NOT_RUNNING"

- name: Check if /etc/containerd/config.toml exists
  ansible.builtin.stat:
    path: /etc/containerd/config.toml
  register: containerd_config_toml

- name: Create /etc/containerd/ directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
  when: not containerd_config_toml.stat.exists

- name: Generate default /etc/containterd/config.toml file
  shell: containerd config default | tee /etc/containerd/config.toml
  when: not containerd_config_toml.stat.exists

- name: Run daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes
  when: containerd_status.stdout == "CONTAINERD_NOT_RUNNING"

# sudo systemctl daemon-reload; sudo systemctl start containerd
- name: Enable and start containerd.service
  ansible.builtin.service:
    name: containerd.service
    enabled: yes
    state: restarted
  when: containerd_status.stdout == "CONTAINERD_NOT_RUNNING"

- name: Remove containerd tarball
  ansible.builtin.file:
    path: "/tmp/{{ containerd_tarball_url.split('/')[-1] }}"
    state: absent
