# Install and setup AWS CloudWatch Agent
---
# Ref: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/download-cloudwatch-agent-commandline.html
- name: Install AWS CloudWatch Agent
  ansible.builtin.apt:
    deb: https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb

# The JSON config was originally created by running the following command on an existing EC2 instance with CloudWatch Agent
# $ /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-config-wizard
- name: Copy configuration to EC2
  ansible.builtin.copy:
    src: ../files/cw-agent-config.json
    dest: /opt/aws/amazon-cloudwatch-agent/bin/config.json

- name: Start CloudWatch Agent
  shell: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json -s
