apiVersion: v1
kind: Service
metadata:
  name: heketi
  labels:
    app.kubernetes.io/name: glusterfs
  # namespace: gluster
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: glusterfs
  ports:
    - port: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heketi
  labels:
    app.kubernetes.io/name: glusterfs
  # namespace: gluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: glusterfs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: glusterfs
    spec:
      containers:
        - name: heketi
          image: heketi/heketi:10
          # command: ["/bin/bash", "-c", "--"]
          # args: ["sleep infinity"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: ssh-key-file
              mountPath: /heketi
            - name: config
              mountPath: /etc/heketi
            - name: data
              mountPath: /var/lib/heketi
      volumes:
        - name: ssh-key-file
          secret:
            secretName: heketi-ssh-key-file
        - name: config
          configMap:
            name: heketi-config
        - name: data
          glusterfs:
            endpoints: glusterfs-cluster
            path: heketi-db-volume
