name: CI to Docker Hub for TLS Cert Monitor

on:
  push:
    branches: [ main ]
    paths:
    - 'aws-wordpress/3-app-configuration/tls-cert-monitor/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'aws-wordpress/3-app-configuration/tls-cert-monitor/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./aws-wordpress/3-app-configuration/tls-cert-monitor
          file: ./aws-wordpress/3-app-configuration/tls-cert-monitor/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tls-cert-monitor:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

