# This playbook will setup GlusterFS and Kubernetes via kubeadm
---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
  - block:
    - name: Check for unsupported distribution
      debug:
        msg: "[{{ ansible_distribution }}] is not an acceptable distribution. Only Ubuntu is accepted!"
    - meta: end_play
    when: ansible_distribution != "Ubuntu"


######################################################################
# All servers in the cluster group should have this base configuration
- hosts: cluster
  gather_facts: yes
  become: yes
  tasks:
  - name: Apply base configuration
    include_tasks:
      file: ansible_tasks/base-config.yml
      apply:
        tags: base_config
    tags:
      - base_config

  - name: Setup AWS CloudWatch Agent
    include_tasks:
      file: ansible_tasks/setup-aws-cw-agent.yml
      apply:
        tags: install_cloudwatch_agent
    tags:
    - install_cloudwatch_agent

  - name: Install and Enable Gluster Server
    include_tasks:
      file: ansible_tasks/setup-gluster.yml
      apply:
        tags: install_setup_gluster
    tags:
    - install_setup_gluster


###############################################################
# Configure Gluster. This needs to happen on a single node only
- hosts: masternode
  gather_facts: no
  become: yes
  tasks:
  - name: Setup Gluster volume via the masternode
    include_tasks:
      file: ansible_tasks/setup-gluster-volume.yml
      apply:
        tags: setup_gluster_volume
    tags:
    - setup_gluster_volume


###############################
# Mount GlusterFS to all nodes
- hosts: cluster
  gather_facts: no
  become: yes
  tasks:
  - name: Mount GlusterFS on all nodes in the cluster (2 replica + 1 arbiter)
    include_tasks:
      file: ansible_tasks/mount-gluster-volume.yml
      apply:
        tags: mount_gluster_volume
    tags:
    - mount_gluster_volume


#################################################
# Install Docker and Kubernetes on all k8s nodes
- hosts: k8s_nodes
  gather_facts: no
  become: yes
  tasks:
  - name: Install and Configure Docker on K8s nodes
    include_role:
      name: roles/docker
      apply:
        tags: install_docker
    tags:
    - install_docker

  - name: Import vars so can be passed into the next include role task
    ansible.builtin.include_vars:
      file: vars/kubernetes.yml
    tags:
    - install_k8s

  - name: Prepare K8s nodes by setting up prerequisites and installing K8s packages
    include_role:
      name: roles/kubernetes/nodes
      apply:
        tags: install_k8s
    tags:
    - install_k8s


######################################
# Create Kubernetes Cluster on Master
- hosts: masternode
  gather_facts: no
  become: yes
  tasks:
  - name: Create Kubernetes Cluster and setup all initial K8s secrets
    include_role:
      name: roles/kubernetes/master
      apply:
        tags: create_k8s_cluster
    tags:
    - create_k8s_cluster

  - name: Get cluster join command
    shell: kubeadm token create $(kubeadm token generate) --print-join-command
    become_user: "{{ ansible_env.SUDO_USER }}"
    register: cluster_join_command
    changed_when: False  # Task will return ok instead of changed
    tags:
    - create_k8s_cluster


##################################
# Join worker nodes to K8s cluster
- hosts: k8s_worker_nodes
  gather_facts: no
  become: yes
  tasks:
  - name: Join nodes to Kubernetes cluster
    include_tasks:
      file: ansible_tasks/k8s-join-nodes-to-cluster.yml
      apply:
        tags: create_k8s_cluster
    tags:
    - create_k8s_cluster


##############################################################
# 'glusterarb' acts as a jump server. Setup tools as required
- hosts: glusterarb
  gather_facts: no
  become: yes
  tasks:
  - name: Import vars so can be used by the next include_task
    ansible.builtin.include_vars:
      file: vars/kubernetes.yml
    tags:
    - jumpbox

  - name: Install tools for Jump Server
    include_tasks:
      file: ansible_tasks/jumpserver-tools-config.yml
      apply:
        tags: jumpbox
    tags:
    - jumpbox


######################################################################
- hosts: masternode,glusterarb
  gather_facts: no
  become: yes
  tasks:
  - name: Configure kubeconfig for jumpserver
    include_tasks:
      file: ansible_tasks/jumpserver-kubeconfig.yml
      apply:
        tags: jumpbox,kubeconfig
    tags:
    - jumpbox
    - kubeconfig
