# This playbook will setup GlusterFS and Kubernetes via kubeadm
---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
  - block:
    - name: Check for unsupported distribution
      debug:
        msg: "[{{ ansible_distribution }}] is not an acceptable distribution. Only Ubuntu is accepted!"
    - meta: end_play
    when: ansible_distribution != "Ubuntu"


######################################################################
# All servers in the cluster group should have this base configuration
- hosts: cluster
  gather_facts: yes
  become: yes
  vars:
    # The 2 etc_hosts vars is referenced within the base-config.yml
    etc_hosts_local: |
        192.168.0.10 masternode.lexd.local
        192.168.0.11 workernode1.lexd.local
        192.168.0.12 glusterarb.lexd.local
    etc_hosts_aws: |
        10.0.10.10 masternode.lexd.local
        10.0.10.11 workernode1.lexd.local
        10.0.10.12 glusterarb.lexd.local
  tasks:
  - name: Apply base configuration
    include_tasks: ansible_tasks/base-config.yml

  - name: Setup AWS CloudWatch Agent
    include_tasks: ansible_tasks/setup-aws-cw-agent.yml

  - name: Install and Enable Gluster Server
    include_tasks: ansible_tasks/setup-gluster.yml


###############################################################
# Configure Gluster. This needs to happen on a single node only
- hosts: masternode
  gather_facts: no
  become: yes
  tasks:
  - name: Setup Gluster volume via the masternode
    include_tasks: ansible_tasks/setup-gluster-volume.yml


###############################
# Mount GlusterFS to all nodes
- hosts: cluster
  gather_facts: no
  become: yes
  tasks:
  - name: Mount GlusterFS on all nodes in the cluster (2 replica + 1 arbiter)
    include_tasks: ansible_tasks/mount-gluster-volume.yml


#################################################
# Install Docker and Kubernetes on all k8s nodes
- hosts: k8s_nodes
  gather_facts: no
  become: yes
  tasks:
  - name: Install and Configure Docker
    include_role:
      name: roles/docker

  - name: Prepare K8s nodes by setting up prerequisites and installing K8s packages
    include_role:
      name: roles/kubernetes/nodes

##################################################
# Create Kubernetes Cluster using the master node
- hosts: masternode
  gather_facts: no
  become: yes
  tasks:
  - name: Include Kubernetes-Master Role
    include_role:
      name: roles/kubernetes/master
